name: Update GitHub Profile

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: ${{ github.repository_owner }}
          theme: dark
          show_icons: true

      - name: Update GitHub Streak
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          username: ${{ github.repository_owner }}
          theme: dark

      - name: Generate GitHub Activity Graph
        uses: Ashutosh00710/github-readme-activity-graph@main
        with:
          username: ${{ github.repository_owner }}
          theme: github

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Auto-update README" || echo "No changes to commit"
          git push
