name: Update GitHub Profile

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Manually Fetch GitHub Stats
        run: |
          git clone https://github.com/anuraghazra/github-readme-stats.git
          cd github-readme-stats
          chmod +x action.yml
          username: ${{ github.repository_owner }}
          theme: dark
          show_icons: true

      - name: Update GitHub Streak
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          username: ${{ github.repository_owner }}
          theme: dark

      - name: Generate GitHub Activity Graph
        uses: Ashutosh00710/github-readme-activity-graph@main
        with:
          username: ${{ github.repository_owner }}
          theme: github

          
